# Generated by Django 3.1.6 on 2021-02-19 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('asset_category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sold_amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bought_amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bought_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_bought', to='quickstart.asset')),
                ('fee_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_fee', to='quickstart.asset')),
                ('sold_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sold', to='quickstart.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=8, max_digits=16)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('assets', models.ManyToManyField(to='quickstart.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
